version: "3.8"
services:
  app:
    container_name: "rocket"
    build: .
    ports:
      - "8000:6666"
    env_file: .env
    depends_on:
      - db
  db:
    container_name: irdb
    image: postgres
    environment:
      POSTGRES_USER: yellowhatpro
      POSTGRES_DB: irdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - irdb-data:/data/db
volumes:
  irdb-data: {}